apiVersion: apps/v1
kind: Deployment
metadata:
    name: media
    namespace: staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: media
    template:
        metadata:
            labels:
                app: media
        spec:
            serviceAccountName: media
            containers:
                - name: media
                  image: lebaoo12/yas-media:main
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: media
    namespace: staging
---
apiVersion: v1
kind: Service
metadata:
    name: media
    namespace: staging
spec:
    selector:
        app: media
    ports:
        - port: 80
          targetPort: 8080
