apiVersion: v1
kind: ServiceAccount
metadata: { name: media, namespace: staging }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: media, namespace: staging }
spec:
    replicas: 1
    selector: { matchLabels: { app: media } }
    template:
        metadata: { labels: { app: media } }
        spec:
            serviceAccountName: media
            containers:
                - name: media
                  image: lebaoo12/yas-media:main
                  ports: [{ containerPort: 8080 }]
                  env:
                      - {
                            name: SPRING_DATASOURCE_URL,
                            value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/staging_media",
                        }
                      - { name: SPRING_DATASOURCE_USERNAME, value: "admin" }
                      - { name: SPRING_DATASOURCE_PASSWORD, value: "admin" }
                      - { name: SERVER_PORT, value: "8080" }
                      - { name: SERVER_SERVLET_CONTEXT_PATH, value: "/media" }
                      - { name: JAVA_TOOL_OPTIONS, value: "-Xmx512m" }
                  resources: { requests: { memory: "256Mi", cpu: "50m" } }
---
apiVersion: v1
kind: Service
metadata: { name: media, namespace: staging }
spec:
    selector: { app: media }
    ports: [{ name: http, port: 80, targetPort: 8080 }]
