apiVersion: apps/v1
kind: Deployment
metadata:
    name: order
    namespace: staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: order
    template:
        metadata:
            labels:
                app: order
        spec:
            serviceAccountName: order
            containers:
                - name: order
                  image: lebaoo12/yas-order:main
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: order
    namespace: staging
---
apiVersion: v1
kind: Service
metadata:
    name: order
    namespace: staging
spec:
    selector:
        app: order
    ports:
        - port: 80
          targetPort: 8080
