apiVersion: v1
kind: ServiceAccount
metadata: { name: order, namespace: staging }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: order, namespace: staging }
spec:
    replicas: 1
    selector: { matchLabels: { app: order } }
    template:
        metadata: { labels: { app: order } }
        spec:
            serviceAccountName: order
            containers:
                - name: order
                  image: lebaoo12/yas-order:main
                  ports: [{ containerPort: 8080 }]
                  env:
                      - {
                            name: SPRING_DATASOURCE_URL,
                            value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/staging_order",
                        }
                      - { name: SPRING_DATASOURCE_USERNAME, value: "admin" }
                      - { name: SPRING_DATASOURCE_PASSWORD, value: "admin" }
                      - { name: SERVER_PORT, value: "8080" }
                      - { name: SERVER_SERVLET_CONTEXT_PATH, value: "/order" }
                      - { name: YAS_SERVICES_CART, value: "http://cart/cart" }
                      - {
                            name: YAS_SERVICES_CUSTOMER,
                            value: "http://customer/customer",
                        }
                      - {
                            name: YAS_SERVICES_PRODUCT,
                            value: "http://product/product",
                        }
                      - { name: YAS_SERVICES_TAX, value: "http://tax/tax" }
                      - { name: JAVA_TOOL_OPTIONS, value: "-Xmx512m" }
                  resources: { requests: { memory: "256Mi", cpu: "50m" } }
---
apiVersion: v1
kind: Service
metadata: { name: order, namespace: staging }
spec:
    selector: { app: order }
    ports: [{ name: http, port: 80, targetPort: 8080 }]
