apiVersion: v1
kind: ServiceAccount
metadata: { name: inventory, namespace: dev }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: inventory, namespace: dev }
spec:
    replicas: 1
    selector: { matchLabels: { app: inventory } }
    template:
        metadata: { labels: { app: inventory } }
        spec:
            serviceAccountName: inventory
            containers:
                - name: inventory
                  image: lebaoo12/yas-inventory:main
                  ports: [{ containerPort: 8080 }]
                  env:
                      - {
                            name: SPRING_DATASOURCE_URL,
                            value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/dev_inventory",
                        }
                      - { name: SPRING_DATASOURCE_USERNAME, value: "admin" }
                      - { name: SPRING_DATASOURCE_PASSWORD, value: "admin" }
                      - { name: SERVER_PORT, value: "8080" }
                      - {
                            name: SERVER_SERVLET_CONTEXT_PATH,
                            value: "/inventory",
                        }
                      - {
                            name: YAS_SERVICES_PRODUCT,
                            value: "http://product/product",
                        }
                      - {
                            name: YAS_SERVICES_LOCATION,
                            value: "http://location/location",
                        }
                      - { name: JAVA_TOOL_OPTIONS, value: "-Xmx512m" }
                  resources: { requests: { memory: "256Mi", cpu: "50m" } }
---
apiVersion: v1
kind: Service
metadata: { name: inventory, namespace: dev }
spec:
    selector: { app: inventory }
    ports: [{ name: http, port: 80, targetPort: 8080 }]
