apiVersion: v1
kind: ServiceAccount
metadata: { name: tax, namespace: dev }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: tax, namespace: dev }
spec:
    replicas: 1
    selector: { matchLabels: { app: tax } }
    template:
        metadata: { labels: { app: tax } }
        spec:
            serviceAccountName: tax
            containers:
                - name: tax
                  image: lebaoo12/yas-tax:main
                  ports: [{ containerPort: 8080 }]
                  env:
                      - {
                            name: SPRING_DATASOURCE_URL,
                            value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/dev_tax",
                        }
                      - { name: SPRING_DATASOURCE_USERNAME, value: "admin" }
                      - { name: SPRING_DATASOURCE_PASSWORD, value: "admin" }
                      - { name: SERVER_PORT, value: "8080" }
                      - { name: SERVER_SERVLET_CONTEXT_PATH, value: "/tax" }
                      - {
                            name: YAS_SERVICES_LOCATION,
                            value: "http://location/location",
                        }
                      - { name: JAVA_TOOL_OPTIONS, value: "-Xmx512m" }
                  resources: { requests: { memory: "256Mi", cpu: "50m" } }
---
apiVersion: v1
kind: Service
metadata: { name: tax, namespace: dev }
spec:
    selector: { app: tax }
    ports: [{ name: http, port: 80, targetPort: 8080 }]
